<?php
 $aik =  array (
  'sitename' => '极客猿梦',
  'pcdomain' => 'http://vip.zcbboke.com',
  'title' => '极客猿梦vip视频解析-免费看腾讯优酷爱奇艺VIP视频',
  'keywords' => '优酷VIP解析,爱奇艺VIP解析,腾讯VIP解析,乐视VIP解析,芒果VIP解析,全网视频解析,VIP在线解析,视频VIP在线解析,VIP视频在线解析',
  'description' => '本站为广大网友提供优酷VIP解析，爱奇艺VIP解析，腾讯VIP解析，乐视VIP解析，芒果VIP解析等解析服务，让你省去购买视频VIP费用，欢迎大家收藏本站，并将它介绍给您的朋友！',
  'weibourl' => '',
  'weibo' => '',
  'gonggao' => '若视频播放异常，尝试刷新或更换接口即可解决！',
  'gonggaourl' => 'http://zcbboke.com',
  'maurl' => 'http://v.youku.com/v_show/id_XMTI4NTY3MTY1Mg==.html',
  'jiekou1name' => '默认一',
  'jiekou1' => 'http://jqaaa.com/jx.php?url=&url=',
  'jiekou2name' => '推荐二',
  'jiekou2' => 'http://api.47ks.com/webcloud/?v=',
  'jiekou3name' => '线路三',
  'jiekou3' => 'http://api.lilaile.cn/index.php?url=',
  'jiekou4name' => '线路四',
  'jiekou4' => 'http://jiexi.071811.cc/jx2.php?url=',
  'jiekou5name' => '线路五',
  'jiekou5' => 'http://api.xfsub.com/index.php?url=',
  'jiekou6name' => '线路六',
  'jiekou6' => 'http://api.baiyug.cn/vip/?url=',
  'jiekou7name' => '磁力一',
  'jiekou7' => 'https://apiv.ga/magnet/',
  'jiekou8name' => '磁力二',
  'jiekou8' => 'http://api.kltvv.top/api/ap.php?u=',
  'jiekou9name' => '测试线',
  'jiekou9' => 'http://api.662820.com/xnflv/index.php?url=',
  'jiekou10name' => '待添加',
  'jiekou10' => '',
  'topnav' => '',
  'ch1' => '',
  'guanggao' => '',
  'changyan' => '',
  'homelink' => '',
  'icp' => '赣ICP备17015743号.',
  'tongji' => '<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id=\'cnzz_stat_icon_1271245319\'%3E%3C/span%3E%3Cscript src=\'" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1271245319%26show%3Dpic1\' type=\'text/javascript\'%3E%3C/script%3E"));</script>',
  'admin_name' => 'admin',
  'admin_pass' => '3ceb0e9fb16f8673c35f707e8657124a',
  'admin_email' => '861013016@qq.com',
  'hometopnotice' => '',
  'hometopright' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>